export interface EmployeeAnswers {
  companyId?: number,
  age?: number,
  gender?: string,
  hasFamilyHistory?: boolean,
  hasEmployeeHistory?:boolean,
  hasReceivedTreatment?: boolean,
  hasBenefits?: boolean,
  wasDiagnosed?: boolean,
  openToDiscussWorkspace?: boolean,
  talkToSupervisor?: string,
  talkToCoworker?: string,
  race?: string,
  medicalLeave?: string,
  interestOrPleasure?: boolean,
  downDepressedHopeless?: boolean,
  troubleFallingAsleep?: boolean,
  tiredLittleEnergy?: boolean,
  poorAppetiteOvereating?: boolean,
  feelingBad?: boolean,
  troubleConcentrating?: boolean,
  slowOrFast?: boolean,
  betterOfDead?: boolean,
  nervousAnxious?: boolean,
  cantStopWorrying?: boolean,
  worryingToMuch?: boolean,
  troubleRelaxing?: boolean,
  easilyAnnoyed?: boolean,
  feelingAfraid?: boolean
}